export const foods = 
[
    {
        id: '1',
        image :"./pic/menu/chicken-tinga-taco.avif",
        name: "CHICKEN TINGA TACO",
        priceCents: 249,
        item : 'tacos',
    },

    {
        id: '2',
        image :'./pic/menu/spicy-grilled-chicken-tacos.avif',
        name: "SPICY GRILLED CHICKEN TACOS",
        priceCents: 249,
        item : 'tacos',
    },
    {
        id : '3',
        image : './pic/menu/buffalo-chicken-tacos.avif',
        name : 'BUFFALO CHICKEN TACOS',
        priceCents : 169,
        item : 'tacos',
    },
    {
        id : '4',
        image : "./pic/menu/sesame-chicken-tacos.avif",
        name : "SESAME CHICKEN TACOS",
        priceCents : 178,
        item : 'tacos',
    },
    {
        id : '5',
        image : './pic/menu/southern-fried-chicken.avif',
        name  : 'SOUTHERN FIRED CHICKEN',
        priceCents : 269,
        item : 'tacos',
    },
    {
        id : '6',
        image :"./pic/menu/poblano onion.avif",
        name  : 'SPICY CHICKEN WITH POBLANO & ONION',
        priceCents : 195,
        item : 'tacos',
    },
    {
        id : '7',
        image : "./pic/menu/beef and potato-tacos.avif",
        name : 'BEEF & POTATOS TACOS',
        priceCents : 250,
        item : 'tacos',
    },
    {
        id : '8',
        image : "./pic/menu/steak-tacos.avif",
        name : 'STEAK TACOS',
        priceCents : 321,
        item : 'tacos',
    },
    {
        id : '9',
        image :"./pic/menu/short rib tacos.avif",
        name : 'BEEF SHORT RIB TACOS',
        priceCents : 345,
        item : 'tacos',
    },
    {
        id : '10',
        image:"./pic/menu/szechuan-beef-tacos.avif",
        name : 'SZECHUAN BEEF TACOS',
        priceCents : 312,
        item : 'tacos',
    },
    {
        id : '11',
        image : "./pic/menu/carnitas tacos.avif",
        name : ' PORK CARNITAS TACOS',
        priceCents : 278,
        item : 'tacos',
    },
    {
        id : '12',
        image : "./pic/menu/guava bbq pork tacos.avif",
        name  : 'GUAVA BBQ PORK TACOS',
        priceCents :214,
        item : 'tacos',
    },
    {
        id :'13',
        image : './pic/menu/chicken tinga bowl burrito.avif',
        name  : 'CHICKEN TINGA BOWL/BURRITO',
        priceCents : 124,
        item : 'burritos'
    },
    {
        id : '14',
        image : './pic/menu/spicy grilled chicken bowl burrito.avif',
        name  : 'SPICY GRILLED CHICKEN BOWL/BURRITO',
        priceCents : 167,
        item : 'burritos',
    },
    {
        id : '15',
        image : './pic/menu/spicy chicken with poblano and onion bowl burrito.avif',
        name : 'SPICY CHICKEN WITH POBLANO & ONION BOWL/BURRITO',
        priceCents : 137,
        item : 'burritos',
    },
    {
        id : '16',
        image : "./pic/menu/sesame chicken bowl.avif",
        name : 'SESAME CHICKEN BOWL/BURRITO',
        priceCents : 346,
        item : 'burritos',
    },
    {
        id : '17',
        image : './pic/menu/southern fried chicken bowl.avif',
        name : 'SOUTHERN FRIED CHICKEN BOWL/BURRITO',
        priceCents : 346,
        item : 'burritos',
    },
    {
        id : '18',
        image : './pic/menu/buffalo chicken bowl.avif',
        name : 'BUFFALO CHICKEN BOWL/BURRITO',
        priceCents : 346,
        item : 'burritos',
    },
    {
        id : '19',
        image : './pic/menu/narciso club bowl.avif',
        name : 'NARCISO CLUB BOWL/BURRITO',
        priceCents : 409,
        item : 'burritos',
    },
    {
        id : '20',
        image : './pic/special menu/1.avif',
        name : '3 BIRRIA TACOS',
        priceCents : 521,
        item : 'specialties',
    },
    {
        id : '21',
        image : './pic/special menu/birria quesadilla.avif',
        name : 'BIRRIA QUESADILLA',
        priceCents :524,
        item : 'specialties',
    },
    {
        id : '22',
        image : './pic/special menu/3 cuban tacos.avif',
        name : '3 CUBAN TACOS',
        priceCents : 576,
        item : 'specialties',
    },
    {
        id : '23',
        image : './pic/special menu/3 pollo asado tacos.avif',
        name : '3 POLLO ASADO TACOS',
        priceCents : 521,
        item : 'specialties',
    }

];
